# Week 4 — Math Intuition for ML + Mini Project
**AI/ML Internship Program — Month 1: Foundations**

This notebook covers:
1. Intuitive math for ML — vectors, matrices, dot products, probability, gradients
2. A hands-on gradient descent demo
3. **Mini Project:** Full EDA on a new, independent dataset — the Palmer Penguins dataset

## 1. Vectors, Matrices, and Dot Products

- A **vector** is just a list of numbers — e.g. a data point with 3 features is a vector in 3D space.
- A **matrix** is a table of numbers — a full dataset (rows = samples, columns = features) is a matrix.
- The **dot product** measures how much two vectors "point in the same direction." In ML, it's the core operation behind predictions: `prediction = weights · features`.
- **Matrix multiplication** is just doing many dot products at once — this is how a whole dataset gets multiplied by a whole set of weights in one shot.

In [1]:
import numpy as np

# A single data point (feature vector): [study_hours, sleep_hours, attendance_pct]
x = np.array([5, 7, 90])

# Weights the model has "learned" for each feature
w = np.array([0.6, 0.3, 0.05])

# Dot product = weighted sum = the model's raw prediction
prediction = np.dot(x, w)
print("Feature vector:", x)
print("Weights:", w)
print("Dot product (prediction):", prediction)

Feature vector: [ 5  7 90]
Weights: [0.6  0.3  0.05]
Dot product (prediction): 9.6


In [2]:
# Matrix multiplication = many dot products at once
# 4 students (rows), 3 features each (columns)
X = np.array([
    [5, 7, 90],
    [2, 5, 60],
    [8, 6, 95],
    [4, 4, 70]
])

predictions = X @ w   # '@' is matrix multiplication in numpy
print("Dataset (4 students x 3 features):\n", X)
print("\nPredictions for all 4 students at once:", predictions)

Dataset (4 students x 3 features):
 [[ 5  7 90]
 [ 2  5 60]
 [ 8  6 95]
 [ 4  4 70]]

Predictions for all 4 students at once: [ 9.6   5.7  11.35  7.1 ]
